version: '3.7'
services:
  web:
    container_name: expense_tracker
    build: .
    command: bash -c "poetry run python expense_tracker/manage.py migrate
      && poetry run python expense_tracker/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: expense_tracker_db
    volumes:
      - postgres_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=expense_tracker
    ports:
      - 5432:5432

volumes:
  postgres_data: