databases:
  - name: expense_tracker_db
    databaseName: expense_tracker_db
    user: postgres

services:
  - type: web
    name: expense_tracker
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn settings.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense_tracker_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4