# Generated by Django 4.0.5 on 2022-08-27 05:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('day_limit', models.PositiveIntegerField(default=0, verbose_name='Ежедневный лимит')),
                ('week_limit', models.PositiveIntegerField(default=0, verbose_name='Еженедельный лимит')),
                ('month_limit', models.PositiveIntegerField(blank=True, default=0, verbose_name='Ежемесячный лимит')),
            ],
            options={
                'verbose_name': 'Профили',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Сумма')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.category', verbose_name='Категория')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Расходы',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date', 'category'],
            },
        ),
    ]
