# Generated by Django 4.0.5 on 2022-06-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
