# Generated by Django 4.0.5 on 2022-06-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0005_alter_expense_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='namecat',
        ),
    ]
