# Generated by Django 4.0.5 on 2022-06-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0006_rename_name_category_namecat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='namecat',
            new_name='name',
        ),
    ]
