# Generated by Django 4.0.5 on 2022-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0007_rename_namecat_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='limit_flag',
            field=models.BooleanField(default=False),
        ),
    ]
