# Generated by Django 4.0.5 on 2022-06-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(to='expense_tracker.category'),
        ),
    ]
