# Generated by Django 4.0.5 on 2022-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0011_alter_category_expense_alter_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(null=True, to='expense_tracker.category'),
        ),
    ]
