# Generated by Django 4.0.5 on 2022-06-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0012_alter_profile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(to='expense_tracker.category'),
        ),
    ]
