# Generated by Django 4.0.5 on 2022-06-26 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0015_alter_category_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense_tracker.expense'),
        ),
    ]
