# Generated by Django 4.0.5 on 2022-06-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0017_alter_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(to='expense_tracker.category'),
        ),
    ]
