# Generated by Django 4.0.5 on 2022-06-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0018_remove_category_user_alter_profile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(related_name='users', to='expense_tracker.category'),
        ),
    ]
