# Generated by Django 4.0.5 on 2022-07-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0030_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'category'], 'verbose_name': 'Расходы', 'verbose_name_plural': 'Расходы'},
        ),
    ]
