# Generated by Django 4.0.5 on 2022-07-28 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense_tracker', '0031_alter_expense_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Дата')),
                ('max', models.FloatField(default=0.0, verbose_name='Максимальная трата')),
                ('min', models.FloatField(default=0.0, verbose_name='Минимальная трата')),
                ('total', models.FloatField(default=0.0, verbose_name='Итого')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
