# Generated by Django 4.0.5 on 2022-07-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0033_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-date', 'user'], 'verbose_name': 'Еженедельные отчеты', 'verbose_name_plural': 'Еженедельные отчеты'},
        ),
    ]
