# Generated by Django 4.0.5 on 2022-08-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0034_alter_dailyreport_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
    ]
