# Generated by Django 4.0.5 on 2022-08-02 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0035_delete_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Сумма'),
        ),
    ]
