# Generated by Django 4.0.5 on 2022-08-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0037_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='limit',
            field=models.PositiveIntegerField(null=True, verbose_name='Лимит'),
        ),
    ]
