# Generated by Django 4.0.5 on 2022-08-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0039_alter_profile_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='limit_flag',
        ),
    ]
