# Generated by Django 4.0.5 on 2022-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0040_remove_profile_limit_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Лимит'),
        ),
    ]
