# Generated by Django 4.0.5 on 2022-08-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0041_alter_profile_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит'),
        ),
    ]
