# Generated by Django 4.0.5 on 2022-08-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0042_alter_profile_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='limit',
        ),
        migrations.AddField(
            model_name='profile',
            name='day_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ежедневный лимит'),
        ),
        migrations.AddField(
            model_name='profile',
            name='week_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Еженедельный лимит'),
        ),
    ]
