# Generated by Django 4.0.5 on 2022-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0043_remove_profile_limit_profile_day_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='day_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Ежедневный лимит'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='week_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Еженедельный лимит'),
        ),
    ]
