# Generated by Django 4.0.5 on 2022-08-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0045_alter_profile_day_limit_alter_profile_week_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='month_limit',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Ежемесячный лимит'),
        ),
    ]
